name: Update documentation

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PR_GITHUB_USER: qe-repo-updater[bot] <152897211+qe-repo-updater[bot]@users.noreply.github.com>

jobs:
  autodoc:
    name: autodoc
    runs-on: ubuntu-latest

    steps:
      - name: Install auto-doc
        uses: taiki-e/install-action@80e6af7a2ec7f280fffe2d0a9d3a12a9d11d86e9 # v2.75.1
        with:
          tool: auto-doc
          fallback: none

      - name: Get Token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app-token
        with:
          app-id: ${{ vars.WORKFLOW_UPDATE_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "${{ github.event.repository.name}}"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Run auto-doc
        run: |
          #!/usr/bin/env bash

          mapfile -t workflow_files < <(find ".github/workflows" -type f -name "*.yml")
          for workflow_file in "${workflow_files[@]}"; do
            workflow="$(basename "$workflow_file")"
            workflow_name="${workflow%%.yml}"
            workflow_doc="./docs/$workflow_name.md"
            if [[ -f "$workflow_doc" ]]; then
              auto-doc --colMaxWords 100 --reusable --filename "$workflow_file" --output "$workflow_doc"
            else
              echo "Skip $workflow because no documentation"
            fi
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          committer: ${{ env.PR_GITHUB_USER }}
          author: ${{ env.PR_GITHUB_USER }}
          commit-message: "docs: update workflow documentation"
          branch: doc/autodoc
          title: "docs: update workflow documentation"
          body: |
            [auto-doc](https://github.com/tj-actions/auto-doc) made some changes to various README.md files

            Automated changes by [Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
