name: action-dependabot-merge
on:
  workflow_call:
    inputs:
      app_id:
        required: true
        description: The App ID that will modify your github workflows
        type: string
    secrets:
      app_private_key:
        required: true
        description: The private key associated with the App ID

jobs:
  actions_merge:
    runs-on: ubuntu-latest
    name: Dependabot Merge (action changes)
    permissions: {}
    if: |
      github.event.client_payload.base.actor == 'dependabot[bot]'
    steps:
      - name: "Create Token"
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app-token
        with:
          app-id: ${{ inputs.app_id }}
          private-key: ${{ secrets.app_private_key }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name}}
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.event.client_payload.base.ref }}
          persist-credentials: false
      - name: Dependabot Merge
        id: dependabot_merge
        uses: quotidian-ennui/actions-olio/dependabot-merge@83871db203c510c8c8d65292f24ebf5437728e7c # v0.9.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          change_filter: ".github/workflows/**"
