name: action-dependabot-merge
on:
  workflow_call:
    inputs:
      client_id:
        description: "GitHub App Client ID"
        required: true
        type: string

    secrets:
      app_private_key:
        required: true
        description: The private key associated with the App ID

jobs:
  actions_merge:
    runs-on: ubuntu-latest
    name: Dependabot Merge (action changes)
    permissions: {}
    if: |
      github.event.client_payload.base.actor == 'dependabot[bot]'
    steps:
      - name: "Create Token (using client-id)"
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token-client-id
        with:
          client-id: ${{ inputs.client_id }}
          private-key: ${{ secrets.app_private_key }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name}}

      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token-client-id.outputs.token }}
          ref: ${{ github.event.client_payload.base.ref }}
          persist-credentials: false

      - name: Dependabot Merge
        id: dependabot_merge
        uses: quotidian-ennui/actions-olio/dependabot-merge@62c2311929dae0037513a7c06bab420d9d4353d3 # v1.2.1
        with:
          token: ${{ steps.app-token-client-id.outputs.token }}
          change_filter: ".github/workflows/**"
