name: check-pr-with-trigger
on:
  workflow_call:
    inputs:
      dispatch_enabled:
        required: false
        default: true
        description: "Whether to fire the 'dependabot_merge' event"
        type: boolean

permissions: {}

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Changed Files
        # Attempt to figure out what files have changed
        id: changes
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files_yaml: |
            workflows:
              - ".github/workflows/**"
      - name: shellcheck
        uses: reviewdog/action-shellcheck@4c07458293ac342d477251099501a718ae5ef86e # v1.32.0
        with:
          reporter: github-pr-review
          fail_level: error
          check_all_files_with_shebangs: "true"
          github_token: ${{ secrets.github_token }}
      - name: actionlint
        uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72.0
        if: steps.changes.outputs.workflows_any_changed == 'true'
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_level: error

  # Check the PR title conforms to 'conventional'
  pr-title:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          regexp="^(build|ci|docs|feat|fix|perf|refactor|style|test|chore|deps)(\(.+\))?(!)?: "
          if [[ ! $PR_TITLE =~ $regexp ]]; then
            echo "PR Title is not 'conventional' matching $regexp" >> "$GITHUB_STEP_SUMMARY"
            exit 1
          fi

  dependabot-merge-trigger:
    needs:
      - reviewdog
      - pr-title
    permissions:
      contents: write
      pull-requests: read
    if: |
      github.actor == 'dependabot[bot]' &&
      github.event_name == 'pull_request' &&
      inputs.dispatch_enabled == true
    runs-on: ubuntu-latest
    steps:
      - name: dispatch
        uses: quotidian-ennui/actions-olio/pr-trigger@83871db203c510c8c8d65292f24ebf5437728e7c # v0.9.1
        with:
          event_type: "dependabot-merge"
