name: create-release
on:
  workflow_call:
    inputs:
      make_latest:
        description: "This is the latest release"
        required: false
        default: true
        type: boolean
      draft:
        description: "This is a draft release"
        required: false
        default: false
        type: boolean
    secrets:
      token:
        required: true
        description: Token for generating the release

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Generate changelog
        uses: orhun/git-cliff-action@c93ef52f3d0ddcdcc9bd5447d98d458a11cd4f72 # v4.7.1
        id: changelog
        with:
          args: --current --github-repo "${{ github.repository }}"
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_TOKEN: ${{ secrets.token }}
      - name: Create Release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          token: ${{ secrets.token }}
          bodyFile: ${{ steps.changelog.outputs.changelog }}
          draft: ${{ inputs.draft }}
          makeLatest: ${{ inputs.make_latest }}
