name: dismiss-dependabot-alerts
on:
  workflow_call:
    inputs:
      client_id:
        description: "GitHub App Client ID with permission to manage dependabot alerts"
        required: true
        type: string
      dismissal_file:
        description: The file that contains the ignore directives (defaults to .github/dismiss-alerts.yml)
        required: false
        default: ".github/dismiss-alerts.yml"
        type: string
    secrets:
      app_private_key:
        required: true
        description: The private key associated with the App ID

permissions: {}
jobs:
  dismiss-alerts:
    timeout-minutes: 2
    name: dismiss-alerts
    runs-on: ubuntu-latest
    steps:
      - name: "Create Token"
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ inputs.client_id }}
          private-key: ${{ secrets.app_private_key }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name}}
          permission-vulnerability-alerts: write
      - name: "Checkout"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          token: ${{ steps.app-token.outputs.token }}
      - name: "Dismiss alerts"
        id: dismiss-alerts
        uses: quotidian-ennui/actions-olio/dismiss-dependabot-alerts@20d61b495f9f57f9103dd8f052d5808370d5ce8b # v1.2.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          dismissal_file: ${{ inputs.dismissal_file }}
